version: '3.4'

services:
  web_api:
    image: web_api
    container_name: web_api_application
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=7sM8V2KiKYv4zagGvgGQ
